AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  StarWarsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./dist/serverless.handler
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 100
      Environment:
        Variables:
          NODE_ENV: production
          MONGOOSE_URL: mongodb://localhost:27017/starwars
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  StarWarsApi:
    Description: 'API Gateway endpoint URL for the HelloWorld function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'